import { ThemeDefinition } from '../types';

export const SOLARIZED_LIGHT_THEME: ThemeDefinition = {
  id: 'solarized-light',
  name: 'Solarized Light',
  description: 'Warm cream and sepia tones designed to reduce eye strain during daylight reading.',
  author: 'Ethan Schoonover',
  type: 'light',
  isPreinstalled: true,
  isBuiltIn: true,
  hasGradient: false,
  previewColors: ['#eae3c6', '#eee8d5', '#fdf6e3', '#d33682'],
  variables: {
    bgApp: '#e3dbb8',
    bgTopBar: '#eae3c6',
    bgRibbon: '#ebe4c8',
    bgSidebar: '#eee8d5',
    bgSidebarHover: '#e2dbbe',
    bgSidebarActive: '#d6cca7',
    bgMain: '#fdf6e3',
    bgCard: '#fdf6e3',
    bgCardHover: '#f5eed7',
    bgPopover: '#fdf6e3',
    bgInput: '#eee8d5',
    bgInputFocus: '#ffffff',
    bgTabActive: '#fdf6e3',
    bgTabHover: '#f5eed7',
    bgTabInactive: 'transparent',
    tabCornerFill: '#fdf6e3',
    tabCornerHoverFill: '#f5eed7',
    bgStatusBar: '#eee8d5',
    borderSubtle: '#ded6b5',
    borderBase: '#d3cbb0',
    borderStrong: '#b58900',
    textPrimary: '#073642',
    textSecondary: '#586e75',
    textMuted: '#657b83',
    textFaint: '#93a1a1',
    accent: '#d33682',
    accentHover: '#cb4b16',
    accentActive: '#b58900',
    accentSubtle: 'rgba(211, 54, 130, 0.15)',
    accentGradient: 'linear-gradient(135deg, #d33682 0%, #cb4b16 100%)',
    selectionBg: '#eee8d5',
    selectionText: '#586e75',
    codeBg: '#eee8d5',
    codeText: '#cb4b16',
    tooltipBg: '#073642',
    tooltipText: '#fdf6e3',
    tooltipMuted: '#93a1a1',
    tooltipBorder: '#586e75',
  },
};
